//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace collegeModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class collegeEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new collegeEntities object using the connection string found in the 'collegeEntities' section of the application configuration file.
        /// </summary>
        public collegeEntities() : base("name=collegeEntities", "collegeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new collegeEntities object.
        /// </summary>
        public collegeEntities(string connectionString) : base(connectionString, "collegeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new collegeEntities object.
        /// </summary>
        public collegeEntities(EntityConnection connection) : base(connection, "collegeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AptiQuestion> AptiQuestions
        {
            get
            {
                if ((_AptiQuestions == null))
                {
                    _AptiQuestions = base.CreateObjectSet<AptiQuestion>("AptiQuestions");
                }
                return _AptiQuestions;
            }
        }
        private ObjectSet<AptiQuestion> _AptiQuestions;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AptiQuestions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAptiQuestions(AptiQuestion aptiQuestion)
        {
            base.AddObject("AptiQuestions", aptiQuestion);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="collegeModel", Name="AptiQuestion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AptiQuestion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AptiQuestion object.
        /// </summary>
        /// <param name="questionId">Initial value of the QuestionId property.</param>
        /// <param name="questionStatement">Initial value of the QuestionStatement property.</param>
        /// <param name="option1">Initial value of the Option1 property.</param>
        /// <param name="option2">Initial value of the Option2 property.</param>
        /// <param name="option3">Initial value of the Option3 property.</param>
        /// <param name="option4">Initial value of the Option4 property.</param>
        /// <param name="correctOption">Initial value of the CorrectOption property.</param>
        public static AptiQuestion CreateAptiQuestion(global::System.Int64 questionId, global::System.String questionStatement, global::System.String option1, global::System.String option2, global::System.String option3, global::System.String option4, global::System.Int16 correctOption)
        {
            AptiQuestion aptiQuestion = new AptiQuestion();
            aptiQuestion.QuestionId = questionId;
            aptiQuestion.QuestionStatement = questionStatement;
            aptiQuestion.Option1 = option1;
            aptiQuestion.Option2 = option2;
            aptiQuestion.Option3 = option3;
            aptiQuestion.Option4 = option4;
            aptiQuestion.CorrectOption = correctOption;
            return aptiQuestion;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 QuestionId
        {
            get
            {
                return _QuestionId;
            }
            set
            {
                if (_QuestionId != value)
                {
                    OnQuestionIdChanging(value);
                    ReportPropertyChanging("QuestionId");
                    _QuestionId = StructuralObject.SetValidValue(value, "QuestionId");
                    ReportPropertyChanged("QuestionId");
                    OnQuestionIdChanged();
                }
            }
        }
        private global::System.Int64 _QuestionId;
        partial void OnQuestionIdChanging(global::System.Int64 value);
        partial void OnQuestionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String QuestionStatement
        {
            get
            {
                return _QuestionStatement;
            }
            set
            {
                OnQuestionStatementChanging(value);
                ReportPropertyChanging("QuestionStatement");
                _QuestionStatement = StructuralObject.SetValidValue(value, false, "QuestionStatement");
                ReportPropertyChanged("QuestionStatement");
                OnQuestionStatementChanged();
            }
        }
        private global::System.String _QuestionStatement;
        partial void OnQuestionStatementChanging(global::System.String value);
        partial void OnQuestionStatementChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Option1
        {
            get
            {
                return _Option1;
            }
            set
            {
                OnOption1Changing(value);
                ReportPropertyChanging("Option1");
                _Option1 = StructuralObject.SetValidValue(value, false, "Option1");
                ReportPropertyChanged("Option1");
                OnOption1Changed();
            }
        }
        private global::System.String _Option1;
        partial void OnOption1Changing(global::System.String value);
        partial void OnOption1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Option2
        {
            get
            {
                return _Option2;
            }
            set
            {
                OnOption2Changing(value);
                ReportPropertyChanging("Option2");
                _Option2 = StructuralObject.SetValidValue(value, false, "Option2");
                ReportPropertyChanged("Option2");
                OnOption2Changed();
            }
        }
        private global::System.String _Option2;
        partial void OnOption2Changing(global::System.String value);
        partial void OnOption2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Option3
        {
            get
            {
                return _Option3;
            }
            set
            {
                OnOption3Changing(value);
                ReportPropertyChanging("Option3");
                _Option3 = StructuralObject.SetValidValue(value, false, "Option3");
                ReportPropertyChanged("Option3");
                OnOption3Changed();
            }
        }
        private global::System.String _Option3;
        partial void OnOption3Changing(global::System.String value);
        partial void OnOption3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Option4
        {
            get
            {
                return _Option4;
            }
            set
            {
                OnOption4Changing(value);
                ReportPropertyChanging("Option4");
                _Option4 = StructuralObject.SetValidValue(value, false, "Option4");
                ReportPropertyChanged("Option4");
                OnOption4Changed();
            }
        }
        private global::System.String _Option4;
        partial void OnOption4Changing(global::System.String value);
        partial void OnOption4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 CorrectOption
        {
            get
            {
                return _CorrectOption;
            }
            set
            {
                OnCorrectOptionChanging(value);
                ReportPropertyChanging("CorrectOption");
                _CorrectOption = StructuralObject.SetValidValue(value, "CorrectOption");
                ReportPropertyChanged("CorrectOption");
                OnCorrectOptionChanged();
            }
        }
        private global::System.Int16 _CorrectOption;
        partial void OnCorrectOptionChanging(global::System.Int16 value);
        partial void OnCorrectOptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] QuestionImage
        {
            get
            {
                return StructuralObject.GetValidValue(_QuestionImage);
            }
            set
            {
                OnQuestionImageChanging(value);
                ReportPropertyChanging("QuestionImage");
                _QuestionImage = StructuralObject.SetValidValue(value, true, "QuestionImage");
                ReportPropertyChanged("QuestionImage");
                OnQuestionImageChanged();
            }
        }
        private global::System.Byte[] _QuestionImage;
        partial void OnQuestionImageChanging(global::System.Byte[] value);
        partial void OnQuestionImageChanged();

        #endregion

    }

    #endregion

}
