<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Management.aspx.cs" Inherits="Admin_Management" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Id" DataSourceID="EntityDataSource1">
                    <Columns>
                        <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                        <asp:BoundField DataField="Password" HeaderText="Password" SortExpression="Password" />
                        <asp:BoundField DataField="EmpId" HeaderText="EmpId" SortExpression="EmpId" ReadOnly="true" />
                    </Columns>
                </asp:GridView>
                <br />
        <asp:DetailsView ID="DetailsView1" runat="server" DataSourceID="EntityDataSource1" DefaultMode="Insert" Height="50px" Width="125px">
            <Fields>
                <asp:CommandField ShowInsertButton="True" />
            </Fields>
        </asp:DetailsView>
                <asp:EntityDataSource ID="EntityDataSource1" runat="server" ConnectionString="name=collegeEntities3" DefaultContainerName="collegeEntities3" EnableDelete="True" EnableFlattening="False" EnableInsert="True" EnableUpdate="True" EntitySetName="Managements">
                </asp:EntityDataSource>
    </div>
    </form>
</body>
</html>
