<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Student.aspx.cs" Inherits="Admin_Student" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
     <asp:GridView ID="GridView3" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Enroll_No" DataSourceID="EntityDataSource3">
                    <Columns>
                        <asp:BoundField DataField="Enroll_No" HeaderText="Enroll_No" ReadOnly="True" SortExpression="Enroll_No" />
                        <asp:BoundField DataField="First_Name" HeaderText="First_Name" SortExpression="First_Name" />
                        <asp:BoundField DataField="Middle_Name" HeaderText="Middle_Name" SortExpression="Middle_Name" />
                        <asp:BoundField DataField="Last_Name" HeaderText="Last_Name" SortExpression="Last_Name" />
                       
                        <asp:BoundField DataField="Branch" HeaderText="Branch" SortExpression="Branch" />
                        <asp:BoundField DataField="Admission_Date" HeaderText="Admission_Date" SortExpression="Admission_Date" />
                        <asp:BoundField DataField="StudentAddress" HeaderText="StudentAddress" SortExpression="StudentAddress" />
                        <asp:BoundField DataField="Email_Id" HeaderText="Email_Id" SortExpression="Email_Id" />
                        <asp:BoundField DataField="ContactNumber" HeaderText="ContactNumber" SortExpression="ContactNumber" />
                        <asp:BoundField DataField="GuardianContact" HeaderText="GuardianContact" SortExpression="GuardianContact" />
                        <asp:BoundField DataField="living_Status" HeaderText="living_Status" SortExpression="living_Status" />
                        <asp:BoundField DataField="Password" HeaderText="Password" SortExpression="Password" />
                        <asp:BoundField DataField="Year" HeaderText="Year" SortExpression="Year" />
                        <asp:BoundField DataField="SecurityQuestion" HeaderText="SecurityQuestion" SortExpression="SecurityQuestion" />
                        <asp:BoundField DataField="SecurityAnswer" HeaderText="SecurityAnswer" SortExpression="SecurityAnswer" />
                        <asp:BoundField DataField="Sex" HeaderText="Sex" SortExpression="Sex" />
                    </Columns>
                </asp:GridView>
                <br />
        <asp:DetailsView ID="DetailsView1" runat="server" DataSourceID="EntityDataSource3" DefaultMode="Insert" Height="50px" Width="125px">
            <Fields>
                <asp:CommandField ShowInsertButton="True" />
            </Fields>
        </asp:DetailsView>
                <asp:EntityDataSource ID="EntityDataSource3" runat="server" ConnectionString="name=CollegeString" DefaultContainerName="CollegeString" EnableDelete="True" EnableFlattening="False" EnableInsert="True" EnableUpdate="True" EntitySetName="Students">
                </asp:EntityDataSource>
    </div>
    </form>
</body>
</html>
